// packages/db/src/index.ts
// 🔴 主平面から使ってよいものだけを export する（docs/05 §2.1）。
//    生 PrismaClient / TenantDb 型 / 生 SQL の入口は export しない。
export { configureTenantDb, disconnectTenantDb } from './client.js';
export type { TenantDbOptions } from './client.js';
export { HostOnlyContextError, requireHost, resolveTenantCtx, TENANT_ROLES } from './context.js';
export type {
  AuthenticatedTenantCtx,
  DeviceKind,
  HostTenantCtx,
  MainSession,
  RequestMeta,
  TenantLifecycleState,
  TenantRole,
} from './context.js';
export {
  AI_ROLES,
  AI_USAGE_FAILURE_KINDS,
  AI_USAGE_PURPOSES,
  ANNOUNCEMENT_KINDS,
  APPROVAL_MODE_CONFIGURABLE_ROLES,
  AUDIT_ACTOR_KINDS,
  AUDIT_DEVICE_KINDS,
  CHAT_THREAD_KINDS,
  CONTRACT_DOCUMENT_EXTERNAL_PROVIDERS,
  CONTRACT_DOCUMENT_SENT_VIAS,
  CONTRACT_KINDS,
  DATA_EXPORT_KINDS,
  DATA_EXPORT_STATUSES,
  EMAIL_DISPATCH_STATUSES,
  EMAIL_EVENT_TYPES,
  EMAIL_RECIPIENT_CLASSES,
  ENGINEER_AVAILABILITIES,
  ENGINEER_SKILL_SOURCES,
  ESIGN_SIGNING_ORDERS,
  EXTENSION_REVIEW_DECISIONS,
  GATE_LAYERS,
  GATE_VERDICTS,
  IMPERSONATION_END_KINDS,
  MATCH_WEIGHT_FACTORS,
  ORDER_PAYMENT_STATES,
  PLATFORM_ROLES,
  PROJECT_STATUSES,
  PROPOSAL_EVENT_KINDS,
  REMOTE_MODES,
  REQUIREMENT_KINDS,
  REVIEW_GATE_EXECUTIONS,
  REVIEW_GATE_TARGET_TYPES,
  SCAN_STATUSES,
  SCHEDULER_RUN_STATUSES,
  SEND_ATTEMPT_ENTITY_TYPES,
  SEND_ATTEMPT_STATUSES,
  SKILL_ALIAS_ORIGINS,
  SKILL_ALIAS_STATUSES,
  SKILL_SHEET_EXTRACTION_STATUSES,
  SUBSCRIPTION_BILLING_STATES,
  TASK_KINDS,
  TASK_STATES,
  TENANT_PURGE_CAUSES,
  TENANT_PURGE_STATUSES,
  TENANT_ROLE_APPROVAL_MODE_VALUES,
  TENANT_SENDING_DOMAIN_STATES,
  TWO_FACTOR_SUBJECT_TYPES,
  USAGE_COUNTER_METRICS,
  USAGE_COUNTER_PERIOD_KINDS,
  WEBHOOK_PROVIDERS,
} from './schema-value-sets.js';
export type {
  AiRole,
  AiUsageFailureKind,
  AiUsagePurpose,
  AnnouncementKind,
  ApprovalModeConfigurableRole,
  AuditActorKind,
  AuditDeviceKind,
  ChatThreadKind,
  ContractDocumentExternalProvider,
  ContractDocumentSentVia,
  ContractKind,
  DataExportKind,
  DataExportStatus,
  EmailDispatchStatus,
  EmailEventType,
  EmailRecipientClass,
  EngineerAvailability,
  EngineerSkillSource,
  EsignSigningOrder,
  ExtensionReviewDecision,
  GateLayer,
  GateVerdict,
  ImpersonationEndKind,
  MatchWeightFactor,
  OrderPaymentState,
  PlatformRole,
  ProjectStatus,
  ProposalEventKind,
  RemoteMode,
  RequirementKind,
  ReviewGateExecution,
  ReviewGateTargetType,
  ScanStatus,
  SchedulerRunStatus,
  SendAttemptEntityType,
  SendAttemptStatus,
  SkillAliasOrigin,
  SkillAliasStatus,
  SkillSheetExtractionStatus,
  SubscriptionBillingState,
  TaskKind,
  TaskState,
  TenantPurgeCause,
  TenantPurgeStatus,
  TenantRoleApprovalModeValue,
  TenantSendingDomainState,
  TwoFactorSubjectType,
  UsageCounterMetric,
  UsageCounterPeriodKind,
  WebhookProvider,
} from './schema-value-sets.js';
export {
  CrossTenantWriteError,
  TENANT_SCOPE_EXCLUDED_MODELS,
  TenantRelationWriteError,
  UnscopedOperationError,
} from './scope-injection.js';
export { withHostTenant, withTenant } from './with-tenant.js';
