// tests/isolation/support/platform-grants.ts
// docs/05 §5.5「運営者に対するマスキング（二層）」第 1 層 = **列単位の GRANT** の期待値。
// `CLAUDE.md` §10.5「運営者にも見せないもの」/ `BR-40` の実装担保。
//
// 🔴 単一出所（T-02-09 申し送り 3 / T-03-08）: `roles.test.ts`（T-01-05 / T-03-08 の完了判定）と
//    `rls-enforced.test.ts`（docs/05 §4.7 #7）の両方がここを実測する。
//    **§5.5 の表と migration 20260904010000 が唯一の真実**であり、ここはそれを写した固定リストである。
//
// 🔴 2 つのリストは向きが違う（どちらも要る）:
//    - `PLATFORM_READ_COLUMN_ALLOWLIST` … 「この列**だけ**が SELECT できる」を表全体で言う。
//      新しい列が増えても GRANT を足さなければテストは green のままだが、**その列は開示されない**
//      （fail-closed）。逆に GRANT を足して許可リストへの追記を忘れると落ちる。
//    - `PLATFORM_READ_COLUMN_DENYLIST` … 「§5.5 が名指しした列は絶対に SELECT できない」を言う。
//      許可リストの写し間違いで非開示列が紛れ込んだ場合に、名指しの側から捕まえる。
//
// 🔴 許可リストに**無い表**は「SELECT 権限 0 件」を意味する（射程外 4 表と `_prisma_migrations` は
//    走査の母集団から外れるため対象外）。表を足したら GRANT と同時にここへ追記する。

/** `app_platform` が `SELECT` できる列（表ごとの完全な一覧）。 */
export const PLATFORM_READ_COLUMN_ALLOWLIST: Record<string, readonly string[]> = {
  tenants: [
    'id',
    'name',
    'environment',
    'lifecycle_state',
    'lifecycle_changed_at',
    'lifecycle_changed_by',
    'suspend_reason',
    'sandbox_expires_at',
    'closing_entered_at',
    'auto_approve_enabled',
    'pii_retention_years',
    'timezone',
    'created_by_platform_user_id',
    'provisioning_request_id',
    'created_at',
  ],
  users: [
    'id',
    'tenant_id',
    'owner_partner_company_id',
    'email',
    'display_name',
    'password_reset_token_hash',
    'password_reset_expires_at',
    'disabled_at',
    'last_login_at',
  ],
  memberships: [
    'id',
    'tenant_id',
    'user_id',
    'role',
    'partner_company_id',
    'joined_at',
    'revoked_at',
  ],
  partner_companies: [
    'id',
    'tenant_id',
    'name',
    'contact_name',
    'contact_email',
    'suspended_at',
    'invited_at',
  ],
  invitations: [
    'id',
    'tenant_id',
    'email',
    'role',
    'partner_company_id',
    'token_hash',
    'expires_at',
    'accepted_at',
    'accepted_user_id',
    'revoked_at',
    'invited_by',
    'invited_by_platform_user_id',
    'created_at',
  ],
  two_factor_credentials: [
    'id',
    'subject_type',
    'subject_id',
    'tenant_id',
    'confirmed_at',
  ],
  tenant_sending_domains: [
    'id',
    'tenant_id',
    'domain',
    'state',
    'ses_identity_arn',
    'ses_tenant_name',
    'dkim_tokens',
    'mail_from_domain',
    'verified_at',
    'last_checked_at',
    'last_failure_reason',
    'registered_by_platform_user_id',
    'created_at',
  ],
  engineers: [
    'id',
    'tenant_id',
    'owner_partner_company_id',
    'availability',
    'available_from',
    'prefecture',
    'remote_mode',
    'retention_expires_at',
    'pii_purged_at',
    'created_at',
    'updated_at',
  ],
  skill_aliases: [
    'id',
    'tenant_id',
    'alias',
    'skill_id',
    'status',
    'origin',
    'proposed_by',
    'decided_by',
    'decided_at',
  ],
  engineer_skills: [
    'id',
    'tenant_id',
    'owner_partner_company_id',
    'engineer_id',
    'skill_id',
    'years_of_experience',
    'level',
    'source',
    'original_label',
    'normalized_at',
    'normalized_role',
    'normalized_prompt_version',
    'normalized_model_id',
  ],
  skill_sheets: [
    'id',
    'tenant_id',
    'owner_partner_company_id',
    'engineer_id',
    'version',
    'content_type',
    'byte_size',
    'scan_status',
    'scan_updated_at',
    'is_latest',
    'uploaded_by',
    'uploaded_at',
    'purged_at',
  ],
  file_scan_results: [
    'id',
    'tenant_id',
    'object_version_id',
    'status',
    'raw_status',
    'received_at',
  ],
  skill_sheet_extractions: [
    'id',
    'tenant_id',
    'owner_partner_company_id',
    'skill_sheet_id',
    'role',
    'prompt_version',
    'model_id',
    'ai_usage_id',
    'status',
    'decided_by',
    'decided_at',
    'created_at',
  ],
  projects: [
    'id',
    'tenant_id',
    'name',
    'public_summary',
    'start_date',
    'prefecture',
    'remote_mode',
    'headcount',
    'status',
    'origin_assignment_id',
    'created_at',
    'updated_at',
  ],
  project_requirements: [
    'id',
    'tenant_id',
    'project_id',
    'kind',
    'skill_id',
    'free_text',
    'required_years',
  ],
  project_visibilities: [
    'id',
    'tenant_id',
    'project_id',
    'partner_company_id',
    'published_at',
    'published_by',
    'revoked_at',
    'review_gate_id',
  ],
  engineer_shares: [
    'id',
    'tenant_id',
    'engineer_id',
    'partner_company_id',
    'shared_at',
    'revoked_at',
    'shared_by',
  ],
  match_candidates: [
    'id',
    'tenant_id',
    'project_id',
    'engineer_id',
    'is_anonymous',
    'score',
    'breakdown',
    'cutoff_reason',
    'weights_snapshot',
    'rationale_role',
    'rationale_prompt_version',
    'rationale_model_id',
    'rationale_ai_usage_id',
    'computed_at',
  ],
  proposal_requests: [
    'id',
    'tenant_id',
    'project_id',
    'engineer_id',
    'partner_company_id',
    'state',
    'expires_at',
    'issued_by',
    'responded_by',
    'responded_at',
    'created_at',
  ],
  proposals: [
    'id',
    'tenant_id',
    'owner_partner_company_id',
    'project_id',
    'engineer_id',
    'proposal_request_id',
    'state',
    'offered_start_date',
    'work_style',
    'draft_role',
    'draft_prompt_version',
    'draft_model_id',
    'draft_ai_usage_id',
    'content_hash',
    'approved_by',
    'approved_by_system',
    'approved_at',
    'submitted_at',
    'last_failure_reason',
    'send_hold_reason_key',
    'send_hold_since',
    'created_by',
    'created_at',
    'updated_at',
  ],
  engineer_snapshots: [
    'id',
    'tenant_id',
    'owner_partner_company_id',
    'proposal_id',
    'available_from',
    'prefecture',
    'remote_mode',
    'skill_sheet_id',
    'frozen_at',
  ],
  proposal_events: [
    'id',
    'tenant_id',
    'owner_partner_company_id',
    'proposal_id',
    'kind',
    'from_state',
    'to_state',
    'actor_user_id',
    'occurred_at',
  ],
  review_gates: [
    'id',
    'tenant_id',
    'owner_partner_company_id',
    'target_type',
    'target_id',
    'content_hash',
    'execution',
    'held_since',
    'pii_verdict',
    'commerce_verdict',
    'consistency_verdict',
    'role',
    'prompt_version',
    'model_id',
    'ai_usage_id',
    'ai_failed',
    'executed_at',
  ],
  chat_threads: [
    'id',
    'tenant_id',
    'kind',
    'project_id',
    'partner_company_id',
    'created_at',
    'last_message_at',
  ],
  thread_participants: [
    'id',
    'tenant_id',
    'thread_id',
    'partner_company_id',
    'joined_at',
    'left_at',
  ],
  messages: [
    'id',
    'tenant_id',
    'owner_partner_company_id',
    'thread_id',
    'sender_user_id',
    'sender_partner_company_id',
    'attachment_scan_status',
    'review_gate_id',
    'sent_at',
    'purged_at',
  ],
  contracts: [
    'id',
    'tenant_id',
    'kind',
    'state',
    'counterparty_partner_company_id',
    'project_id',
    'engineer_id',
    'assignment_id',
    'period_start',
    'period_end',
    'corrects_contract_id',
    'send_failure_reason',
    'send_hold_reason_key',
    'send_hold_since',
    'withdraw_reason',
    'executed_at',
    'expired_at',
    'created_at',
    'updated_at',
  ],
  contract_documents: [
    'id',
    'tenant_id',
    'counterparty_partner_company_id',
    'contract_id',
    'version',
    'template_id',
    'template_version',
    'review_gate_id',
    'scan_status',
    'external_document_id',
    'external_provider',
    'sent_via',
    'requested_at',
    'signed_at',
    'normalized_status',
  ],
  contract_templates: [
    'id',
    'tenant_id',
    'name',
    'kind',
    'version',
    'scan_status',
    'placeholders',
    'is_latest',
    'archived_at',
    'created_by',
    'created_at',
  ],
  orders: [
    'id',
    'tenant_id',
    'counterparty_partner_company_id',
    'contract_id',
    'assignment_id',
    'period_start',
    'period_end',
    'issued_on',
    'payment_state',
    'created_at',
  ],
  assignments: [
    'id',
    'tenant_id',
    'engineer_id',
    'project_id',
    'proposal_id',
    'counterparty_partner_company_id',
    'state',
    'start_date',
    'end_date',
    'actual_leave_date',
    'review_opened_at',
    'reminder30_sent_at',
    'owner_user_id',
  ],
  extension_reviews: [
    'id',
    'tenant_id',
    'assignment_id',
    'opened_at',
    'owner_user_id',
    'role',
    'prompt_version',
    'model_id',
    'ai_usage_id',
    'decision',
    'decided_by',
    'decided_at',
  ],
  tasks: [
    'id',
    'tenant_id',
    'owner_partner_company_id',
    'kind',
    'target_type',
    'target_id',
    'due_on',
    'assignee_user_id',
    'state',
    'auto_generated',
    'completed_at',
  ],
  notifications: [
    'id',
    'tenant_id',
    'recipient_user_id',
    'kind',
    'target_type',
    'target_id',
    'body_key',
    'read_at',
    'email_dispatch_id',
    'suppressed_by_limit',
    'created_at',
  ],
  ai_usage: [
    'id',
    'tenant_id',
    'role',
    'model_id',
    'purpose',
    'prompt_version',
    'target_type',
    'target_id',
    'input_tokens',
    'output_tokens',
    'cache_read_tokens',
    'cache_write_tokens',
    'estimated_cost_usd',
    'attempt_no',
    'succeeded',
    'failure_kind',
    'started_at',
    'finished_at',
  ],
  audit_logs: [
    'id',
    'tenant_id',
    'actor_kind',
    'actor_id',
    'action',
    'target_type',
    'target_id',
    'summary',
    'impersonation_session_id',
    'ip_address',
    'device_kind',
    'created_at',
  ],
  usage_counters: [
    'id',
    'tenant_id',
    'period_kind',
    'period_key',
    'metric',
    'value',
    'reserved_value',
    'observed_at',
  ],
  tenant_esign_connections: [
    'id',
    'tenant_id',
    'provider',
    'external_account_id',
    'base_uri',
    'account_name',
    'connect_config_id',
    'signing_order_default',
    'connected_at',
    'last_verified_at',
    'invalidated_at',
    'connected_by',
  ],
  send_attempts: [
    'id',
    'tenant_id',
    'entity_type',
    'entity_id',
    'attempt_seq',
    'idempotency_key',
    'status',
    'external_id',
    'failure_kind',
    'started_at',
    'settled_at',
    'requested_by',
  ],
  email_dispatches: [
    'id',
    'tenant_id',
    'recipient_class',
    'template_key',
    'dedupe_key',
    'status',
    'held_at',
    'ses_message_id',
    'sent_at',
    'failure_reason',
  ],
  email_events: [
    'id',
    'tenant_id',
    'ses_message_id',
    'event_type',
    'occurred_at',
  ],
  webhook_deliveries: [
    'id',
    'provider',
    'external_event_id',
    'dedupe_key',
    'received_at',
    'processed_at',
    'process_failed_at',
    'failure_reason',
  ],
  data_export_requests: [
    'id',
    'tenant_id',
    'kind',
    'scope',
    'status',
    'requested_by',
    'requested_at',
    'ready_at',
    'expires_at',
  ],
  tenant_purge_runs: [
    'id',
    'tenant_id',
    'cause',
    'status',
    'started_at',
    'completed_at',
    'counts',
    'failure_reason',
  ],
  scheduler_runs: [
    'id',
    'job_name',
    'run_key',
    'started_at',
    'finished_at',
    'status',
    'detail',
  ],
  impersonation_sessions: [
    'id',
    'platform_user_id',
    'tenant_id',
    'reason',
    'started_at',
    'expires_at',
    'ended_at',
    'end_kind',
    'notified_user_ids',
    'notification_failed',
  ],
  announcements: [
    'id',
    'kind',
    'target_tenant_ids',
    'feature_key',
    'enabled',
    'title_key',
    'body_key',
    'reason_key',
    'visible_from',
    'visible_to',
    'created_by',
  ],
  tenant_role_approval_modes: [
    'tenant_id',
    'role',
    'mode',
    'updated_by',
    'updated_at',
  ],
  tenant_role_models: [
    'tenant_id',
    'role',
    'model_id',
    'updated_by',
    'updated_at',
  ],
  tenant_match_weights: [
    'tenant_id',
    'factor',
    'weight',
    'updated_by',
    'updated_at',
  ],
  tenant_monthly_costs: [
    'tenant_id',
    'period_month',
    'revenue_seat_jpy',
    'revenue_overage_jpy',
    'cost_ai_usd',
    'cost_ai_by_role',
    'cost_email_usd',
    'cost_storage_usd',
    'cost_esign_usd',
    'pricing_ruleset_version',
    'storage_bytes_at_month_end',
    'gross_margin_rate',
    'baseline_ratio',
    'quota_consumption_rate',
    'meter_diff_jpy',
    'finalized_at',
    'updated_at',
  ],
  billing_meter_submissions: [
    'tenant_id',
    'event_name',
    'period_end',
    'value',
    'submitted_at',
    'stripe_identifier',
  ],};

/**
 * docs/05 §5.5 が名指しで「`app_platform` に GRANT しない」と定める列。
 *
 * 🔴 T-03-08 で次を追加した（docs/05 §5.5 の表にも追記済み。`CLAUDE.md` §10.5
 *    「運営者に必要なのは『件数・状態・エラー』であって『内容』ではない」の横断適用）:
 *      - 商流（単価）: `engineers` / `engineer_snapshots` / `projects` の `unit_price_min` /
 *        `unit_price_max`、`proposals.offered_unit_price` / `recipient_company_name`
 *      - 内容（自由文・AI 生成物）: `match_candidates.rationale`、
 *        `extension_reviews.facts` / `summary`、`notifications.title` / `body_params`、
 *        `send_attempts.failure_detail`
 *      - 宛先・生ペイロード: `email_dispatches.recipient_email`、`email_events.payload`、
 *        `webhook_deliveries.payload`
 *      - オブジェクトキー: `file_scan_results.object_key`、`data_export_requests.object_key`
 */
export const PLATFORM_READ_COLUMN_DENYLIST: Record<string, readonly string[]> = {
  engineers: [
    'display_name',
    'birth_date',
    'contact_email',
    'contact_phone',
    'affiliation_label',
    'city',
    'preference_note',
    'unit_price_min',
    'unit_price_max',
  ],
  // 🔴 T-05-06: `note`（版のメモ）は利用者の自由入力であり、氏名・案件名・単価が書かれうる
  //    （`CLAUDE.md` §10.5「運営者に必要なのは件数・状態・エラーであって内容ではない」）。
  //    migration 20260909000000 は GRANT を足していない（fail-closed）。ここは名指しの側から固定する。
  skill_sheets: ['object_key', 'note'],
  skill_sheet_extractions: ['payload'],
  projects: ['end_client_name', 'internal_unit_price', 'unit_price_min', 'unit_price_max'],
  engineer_snapshots: [
    'display_name',
    'affiliation_label',
    'skills',
    'careers',
    'unit_price_min',
    'unit_price_max',
  ],
  proposals: [
    'subject',
    'body',
    'draft_body',
    'recipient_email',
    'recipient_company_name',
    'offered_unit_price',
  ],
  proposal_events: ['note', 'attachment_key'],
  review_gates: ['findings', 'ai_warnings'],
  proposal_requests: ['message', 'decline_reason'],
  match_candidates: ['rationale'],
  messages: ['body', 'attachment_key'],
  assignments: ['unit_price'],
  contracts: ['unit_price', 'counterparty_name', 'payment_terms'],
  contract_documents: ['signers', 'object_key', 'merge_result'],
  contract_templates: ['object_key', 'mapping'],
  orders: ['amount'],
  extension_reviews: ['facts', 'summary'],
  notifications: ['title', 'body_params'],
  send_attempts: ['failure_detail'],
  email_dispatches: ['recipient_email'],
  email_events: ['payload'],
  webhook_deliveries: ['payload'],
  file_scan_results: ['object_key'],
  data_export_requests: ['object_key'],
  tenant_esign_connections: [
    'credential_encrypted',
    'connect_hmac_keys_encrypted',
    'webhook_path_secret_encrypted',
  ],
  two_factor_credentials: ['secret_encrypted', 'recovery_code_hashes'],
  users: ['password_hash'],
};

/**
 * 🔴 `app_platform_write` が `tenants` に対して持つ `SELECT` は**この 2 列だけ**である
 *    （Issue #24 の決定 = 既定値 A。docs/05 §5.2 / `P-A-13`）。
 *    テナント開設直後の読み戻し（API-A4 の応答。`INSERT ... RETURNING`）に要る最小である。
 *    🔴 **行全体・他列に広げない** —— 広げると `BR-40` の担保が除外リスト頼みになる。
 */
export const PLATFORM_WRITE_TENANTS_SELECT_COLUMNS = ['id', 'lifecycle_state'] as const;
