// tests/static/support/ui-ratchet-baseline.ts
// 🔴 **UI 刷新のラチェットの凍結スナップショット（2026-09-30 の実体）。**
//    `docs/05` §17.7.2 の ③（行数のスナップショット）と ④（初回の実体で凍結し以後 1 行も追加しない）
//    の両方がこの 1 ファイルに依存する。
//
// ============================================================================
// 🔴 このファイルを編集しない
// ============================================================================
// - **足さない**: キーを足せるなら ④「1 行も追加できない」が成立しない。新しいファイルは最初から
//   semantic トークン / 7 段 / 6 トークン / `PageBody` の幅クラスで書く。
// - **削らない**: 段が進んで掃除が済んだファイルは **`ui-ratchet-allowlist.ts` の側から**外す。
//   ここを削ると ④ の部分集合判定が自明に成り立ち、追加の検知が効かなくなる。
// - **行数を増やさない**: ③ が「増える変更は落ちる」を担保している唯一の根拠である。
//
// ⚠️ 値は `T-22-02` 着手時（2026-09-30）に走査で実測したものである。`SP-22` §3.4-6 の概数
//    （色 1,273 箇所 / spacing 48 種類 / `max-w-*` 86 箇所 / 文字サイズ 832 箇所）は
//    `*.render.test.tsx` を含む grep の概数であり、**実装ファイルだけを AST で数えた本表とは一致しない**
//    （§3.4 / §17.7.1 が「着手時に走査で再実測する」と指示しているのはこのためである）。
//
// 単位は🔴 **「違反を含む行の数」**（同じ行に 3 語あっても 1）。理由は `ui-ratchet.ts` の
// `scanClassViolations` のコメント。

/** (a) 色の直書き — 2026-09-30: 93 ファイル / 1007 行。 */
export const UI_RATCHET_BASELINE_A: ReadonlyMap<string, number> = new Map([
  ['apps/web/app/(main)/(auth)/invite/[token]/invite-form.tsx', 8],
  ['apps/web/app/(main)/(auth)/invite/[token]/page.tsx', 1],
  ['apps/web/app/(main)/(auth)/password-reset/confirm/confirm-form.tsx', 3],
  ['apps/web/app/(main)/(auth)/password-reset/confirm/page.tsx', 1],
  ['apps/web/app/(main)/(auth)/password-reset/page.tsx', 1],
  ['apps/web/app/(main)/(auth)/password-reset/request-form.tsx', 4],
  ['apps/web/app/(main)/(auth)/signin/page.tsx', 1],
  ['apps/web/app/(main)/(auth)/signin/signin-form.tsx', 6],
  ['apps/web/app/(main)/_home/action-queue-section.tsx', 11],
  ['apps/web/app/(main)/_home/home-sections.tsx', 6],
  ['apps/web/app/(main)/_shared/sending-domain-guard-banner.tsx', 1],
  ['apps/web/app/(main)/_shared/sending-domain-status.tsx', 3],
  ['apps/web/app/(main)/_shell/app-shell.tsx', 19],
  ['apps/web/app/(main)/_shell/page-heading.tsx', 4],
  ['apps/web/app/(main)/audit-logs/audit-log-detail.tsx', 11],
  ['apps/web/app/(main)/audit-logs/audit-logs-view.tsx', 8],
  ['apps/web/app/(main)/engineer-shares/engineer-share-screen.tsx', 21],
  ['apps/web/app/(main)/engineers/(list)/error.tsx', 3],
  ['apps/web/app/(main)/engineers/(list)/loading.tsx', 3],
  ['apps/web/app/(main)/engineers/[id]/detail-section.tsx', 3],
  ['apps/web/app/(main)/engineers/[id]/edit/not-found.tsx', 2],
  ['apps/web/app/(main)/engineers/[id]/engineer-proposal-sections.tsx', 13],
  ['apps/web/app/(main)/engineers/[id]/not-found.tsx', 2],
  ['apps/web/app/(main)/engineers/[id]/page.tsx', 13],
  ['apps/web/app/(main)/engineers/[id]/skill-sheets/page.tsx', 1],
  ['apps/web/app/(main)/engineers/[id]/skill-sheets/skill-sheet-screen.tsx', 20],
  ['apps/web/app/(main)/engineers/_form/engineer-form.tsx', 24],
  ['apps/web/app/(main)/engineers/engineer-ledger-screen.tsx', 10],
  ['apps/web/app/(main)/projects/(list)/error.tsx', 3],
  ['apps/web/app/(main)/projects/(list)/loading.tsx', 3],
  ['apps/web/app/(main)/projects/[id]/candidates/candidate-screen.tsx', 33],
  ['apps/web/app/(main)/projects/[id]/candidates/page.tsx', 2],
  ['apps/web/app/(main)/projects/[id]/edit/not-found.tsx', 2],
  ['apps/web/app/(main)/projects/[id]/not-found.tsx', 2],
  ['apps/web/app/(main)/projects/[id]/page.tsx', 2],
  ['apps/web/app/(main)/projects/[id]/project-detail-screen.tsx', 24],
  ['apps/web/app/(main)/projects/[id]/visibility/visibility-screen.tsx', 37],
  ['apps/web/app/(main)/projects/_form/project-form.tsx', 21],
  ['apps/web/app/(main)/projects/project-list-screen.tsx', 7],
  ['apps/web/app/(main)/proposal-requests/[id]/not-found.tsx', 2],
  ['apps/web/app/(main)/proposal-requests/[id]/proposal-request-respond-screen.tsx', 29],
  ['apps/web/app/(main)/proposal-requests/proposal-request-screen.tsx', 14],
  ['apps/web/app/(main)/proposals/(list)/error.tsx', 2],
  ['apps/web/app/(main)/proposals/(list)/loading.tsx', 3],
  ['apps/web/app/(main)/proposals/(list)/proposal-list-screen.tsx', 16],
  ['apps/web/app/(main)/proposals/[id]/approve/not-found.tsx', 2],
  ['apps/web/app/(main)/proposals/[id]/approve/proposal-approval-screen.tsx', 52],
  ['apps/web/app/(main)/proposals/[id]/edit/not-found.tsx', 2],
  ['apps/web/app/(main)/proposals/[id]/interview/not-found.tsx', 2],
  ['apps/web/app/(main)/proposals/[id]/interview/proposal-interview-screen.tsx', 33],
  ['apps/web/app/(main)/proposals/[id]/not-found.tsx', 2],
  ['apps/web/app/(main)/proposals/[id]/proposal-detail-screen.tsx', 64],
  ['apps/web/app/(main)/proposals/_editor/proposal-editor.tsx', 38],
  ['apps/web/app/(main)/proposals/new/page.tsx', 2],
  ['apps/web/app/(main)/proposals/send-failures/error.tsx', 2],
  ['apps/web/app/(main)/proposals/send-failures/loading.tsx', 3],
  ['apps/web/app/(main)/proposals/send-failures/send-failure-screen.tsx', 26],
  ['apps/web/app/(main)/settings/organization/organization-form.tsx', 7],
  ['apps/web/app/(main)/settings/organization/page.tsx', 5],
  ['apps/web/app/(main)/settings/partner-companies/invite-link-panel.tsx', 5],
  ['apps/web/app/(main)/settings/partner-companies/members-panel.tsx', 18],
  ['apps/web/app/(main)/settings/partner-companies/partner-companies-screen.tsx', 28],
  ['apps/web/app/(main)/settings/retention/retention-screen.tsx', 16],
  ['apps/web/app/(main)/settings/sending-domains/sending-domain-screen.tsx', 29],
  ['apps/web/app/(main)/settings/usage/usage-screen.tsx', 39],
  ['apps/web/app/(main)/skills/skill-dictionary-screen.tsx', 17],
  ['apps/web/app/_components/otpauth-qr.tsx', 1],
  ['apps/web/app/admin/_components/console-nav.tsx', 5],
  ['apps/web/app/admin/_components/console-subject.tsx', 2],
  ['apps/web/app/admin/audit-logs/admin-audit-logs-results.tsx', 6],
  ['apps/web/app/admin/audit-logs/admin-audit-logs-view.tsx', 5],
  ['apps/web/app/admin/audit-logs/page.tsx', 2],
  ['apps/web/app/admin/demo/admin-demo-screen.tsx', 23],
  ['apps/web/app/admin/demo/admin-demo-view.tsx', 28],
  ['apps/web/app/admin/layout.tsx', 1],
  ['apps/web/app/admin/monitoring/admin-monitoring-items.tsx', 9],
  ['apps/web/app/admin/monitoring/admin-monitoring-view.tsx', 1],
  ['apps/web/app/admin/monitoring/page.tsx', 2],
  ['apps/web/app/admin/page.tsx', 9],
  ['apps/web/app/admin/signin/admin-signin-form.tsx', 7],
  ['apps/web/app/admin/signin/page.tsx', 2],
  ['apps/web/app/admin/tenants/[id]/contract/deletion-status-screen.tsx', 13],
  ['apps/web/app/admin/tenants/[id]/page.tsx', 17],
  ['apps/web/app/admin/tenants/admin-tenants-list.tsx', 16],
  ['apps/web/app/admin/tenants/new/page.tsx', 4],
  ['apps/web/app/admin/tenants/new/provisioning-form.tsx', 22],
  ['apps/web/app/admin/tenants/page.tsx', 2],
  ['apps/web/app/admin/usage/admin-usage-table.tsx', 18],
  ['apps/web/app/admin/usage/admin-usage-view.tsx', 4],
  ['apps/web/app/admin/usage/page.tsx', 1],
  ['apps/web/app/admin/usage/quota-override-form.tsx', 6],
  ['apps/web/app/global-error.tsx', 3],
  ['apps/web/app/layout.tsx', 1],
]);

/**
 * (b) プリミティブの二重実装（③ `apps/web` 側の宣言）— 2026-09-30: 1 ファイル / 1 行。
 *
 * 🔴 **`docs/05` §17.7.2 は「(b) には許可リストを置かない」と書いているが、それは
 *    `AppShell` が `packages/ui` へ移った後の状態を前提にしている。**
 *    `SP-22` §4.1 の段① の行は「**(e)(h)(i)(b)** が無条件 green」——
 *    つまり (b) が無条件 green になるのは**段① の終わり（`T-22-05`）**である。
 *    `T-22-02` は段① の途中であり、`apps/web/app/(main)/_shell/app-shell.tsx` が
 *    まだ `export function AppShell` を持っている（`T-12-20` の実装）。
 *
 * 🔴 **だから 1 件だけラチェットに載せる。** 赤いまま置くと検査が skip されるか緩められる
 *    （`design-tokens.test.ts` 冒頭が警戒している「先に広げて赤いまま放置する」形）。
 *    ラチェットの ②（未使用なら落ちる）が働くので、`T-22-05` が部品を移した瞬間に
 *    **この 1 行を消さないとテストが落ちる** = §4.1 の段① の完了条件が機械で強制される。
 */
export const UI_RATCHET_BASELINE_B: ReadonlyMap<string, number> = new Map([
  ['apps/web/app/(main)/_shell/app-shell.tsx', 1],
]);

/** (c) 画面の幅指定 — 2026-09-30: 67 ファイル / 78 行。 */
export const UI_RATCHET_BASELINE_C: ReadonlyMap<string, number> = new Map([
  ['apps/web/app/(main)/audit-logs/page.tsx', 1],
  ['apps/web/app/(main)/engineer-shares/page.tsx', 1],
  ['apps/web/app/(main)/engineers/(list)/error.tsx', 1],
  ['apps/web/app/(main)/engineers/(list)/loading.tsx', 1],
  ['apps/web/app/(main)/engineers/(list)/page.tsx', 1],
  ['apps/web/app/(main)/engineers/[id]/edit/not-found.tsx', 1],
  ['apps/web/app/(main)/engineers/[id]/edit/page.tsx', 1],
  ['apps/web/app/(main)/engineers/[id]/not-found.tsx', 1],
  ['apps/web/app/(main)/engineers/[id]/page.tsx', 1],
  ['apps/web/app/(main)/engineers/[id]/skill-sheets/page.tsx', 1],
  ['apps/web/app/(main)/engineers/[id]/skill-sheets/skill-sheet-screen.tsx', 2],
  ['apps/web/app/(main)/engineers/new/page.tsx', 1],
  ['apps/web/app/(main)/page.tsx', 1],
  ['apps/web/app/(main)/projects/(list)/error.tsx', 1],
  ['apps/web/app/(main)/projects/(list)/loading.tsx', 1],
  ['apps/web/app/(main)/projects/(list)/page.tsx', 1],
  ['apps/web/app/(main)/projects/[id]/candidates/page.tsx', 2],
  ['apps/web/app/(main)/projects/[id]/edit/not-found.tsx', 1],
  ['apps/web/app/(main)/projects/[id]/edit/page.tsx', 1],
  ['apps/web/app/(main)/projects/[id]/not-found.tsx', 1],
  ['apps/web/app/(main)/projects/[id]/page.tsx', 2],
  ['apps/web/app/(main)/projects/[id]/visibility/page.tsx', 1],
  ['apps/web/app/(main)/projects/new/page.tsx', 1],
  ['apps/web/app/(main)/proposal-requests/[id]/not-found.tsx', 1],
  ['apps/web/app/(main)/proposal-requests/[id]/page.tsx', 1],
  ['apps/web/app/(main)/proposal-requests/page.tsx', 1],
  ['apps/web/app/(main)/proposals/(list)/error.tsx', 1],
  ['apps/web/app/(main)/proposals/(list)/loading.tsx', 1],
  ['apps/web/app/(main)/proposals/(list)/page.tsx', 1],
  ['apps/web/app/(main)/proposals/[id]/approve/not-found.tsx', 1],
  ['apps/web/app/(main)/proposals/[id]/approve/page.tsx', 1],
  ['apps/web/app/(main)/proposals/[id]/edit/not-found.tsx', 1],
  ['apps/web/app/(main)/proposals/[id]/edit/page.tsx', 1],
  ['apps/web/app/(main)/proposals/[id]/interview/not-found.tsx', 1],
  ['apps/web/app/(main)/proposals/[id]/interview/page.tsx', 1],
  ['apps/web/app/(main)/proposals/[id]/not-found.tsx', 1],
  ['apps/web/app/(main)/proposals/[id]/page.tsx', 1],
  ['apps/web/app/(main)/proposals/new/page.tsx', 2],
  ['apps/web/app/(main)/proposals/send-failures/error.tsx', 1],
  ['apps/web/app/(main)/proposals/send-failures/loading.tsx', 1],
  ['apps/web/app/(main)/proposals/send-failures/page.tsx', 1],
  ['apps/web/app/(main)/settings/organization/page.tsx', 1],
  ['apps/web/app/(main)/settings/partner-companies/members-panel.tsx', 2],
  ['apps/web/app/(main)/settings/partner-companies/page.tsx', 1],
  ['apps/web/app/(main)/settings/partner-companies/partner-companies-screen.tsx', 5],
  ['apps/web/app/(main)/settings/retention/page.tsx', 1],
  ['apps/web/app/(main)/settings/sending-domains/page.tsx', 1],
  ['apps/web/app/(main)/settings/sending-domains/sending-domain-screen.tsx', 1],
  ['apps/web/app/(main)/settings/usage/page.tsx', 1],
  ['apps/web/app/(main)/settings/usage/usage-screen.tsx', 1],
  ['apps/web/app/(main)/skills/page.tsx', 1],
  ['apps/web/app/(main)/skills/skill-dictionary-screen.tsx', 1],
  ['apps/web/app/_components/auth-shell.tsx', 1],
  ['apps/web/app/_components/otpauth-qr.tsx', 1],
  ['apps/web/app/admin/audit-logs/admin-audit-logs-results.tsx', 1],
  ['apps/web/app/admin/audit-logs/page.tsx', 1],
  ['apps/web/app/admin/demo/admin-demo-screen.tsx', 2],
  ['apps/web/app/admin/demo/admin-demo-view.tsx', 1],
  ['apps/web/app/admin/monitoring/page.tsx', 1],
  ['apps/web/app/admin/page.tsx', 1],
  ['apps/web/app/admin/tenants/[id]/contract/deletion-status-screen.tsx', 1],
  ['apps/web/app/admin/tenants/[id]/page.tsx', 2],
  ['apps/web/app/admin/tenants/new/page.tsx', 1],
  ['apps/web/app/admin/tenants/page.tsx', 1],
  ['apps/web/app/admin/usage/page.tsx', 1],
  ['apps/web/app/admin/usage/quota-override-form.tsx', 1],
  ['apps/web/app/global-error.tsx', 1],
]);

/** (f) spacing 7 段 — 2026-09-30: 19 ファイル / 26 行。 */
export const UI_RATCHET_BASELINE_F: ReadonlyMap<string, number> = new Map([
  ['apps/web/app/(main)/(auth)/invite/[token]/invite-form.tsx', 1],
  ['apps/web/app/(main)/(auth)/signin/signin-form.tsx', 1],
  ['apps/web/app/(main)/_shell/app-shell.tsx', 1],
  ['apps/web/app/(main)/audit-logs/audit-log-detail.tsx', 1],
  ['apps/web/app/(main)/audit-logs/audit-logs-view.tsx', 1],
  ['apps/web/app/(main)/engineers/engineer-ledger-screen.tsx', 1],
  ['apps/web/app/(main)/projects/[id]/candidates/candidate-screen.tsx', 1],
  ['apps/web/app/(main)/projects/[id]/visibility/visibility-screen.tsx', 2],
  ['apps/web/app/(main)/proposal-requests/[id]/proposal-request-respond-screen.tsx', 2],
  ['apps/web/app/(main)/proposals/[id]/approve/proposal-approval-screen.tsx', 3],
  ['apps/web/app/(main)/proposals/[id]/proposal-detail-screen.tsx', 2],
  ['apps/web/app/(main)/proposals/_editor/proposal-editor.tsx', 1],
  ['apps/web/app/(main)/proposals/send-failures/send-failure-screen.tsx', 2],
  ['apps/web/app/(main)/settings/usage/usage-screen.tsx', 1],
  ['apps/web/app/admin/signin/admin-signin-form.tsx', 1],
  ['apps/web/app/admin/tenants/new/page.tsx', 1],
  ['apps/web/app/admin/tenants/new/provisioning-form.tsx', 1],
  ['apps/web/app/admin/usage/admin-usage-table.tsx', 2],
  ['apps/web/app/global-error.tsx', 1],
]);

/** (g) 文字サイズ 6 トークン — 2026-09-30: 90 ファイル / 667 行。 */
export const UI_RATCHET_BASELINE_G: ReadonlyMap<string, number> = new Map([
  ['apps/web/app/(main)/(auth)/invite/[token]/invite-form.tsx', 5],
  ['apps/web/app/(main)/(auth)/invite/[token]/page.tsx', 1],
  ['apps/web/app/(main)/(auth)/password-reset/confirm/confirm-form.tsx', 3],
  ['apps/web/app/(main)/(auth)/password-reset/confirm/page.tsx', 1],
  ['apps/web/app/(main)/(auth)/password-reset/page.tsx', 1],
  ['apps/web/app/(main)/(auth)/password-reset/request-form.tsx', 4],
  ['apps/web/app/(main)/(auth)/signin/page.tsx', 1],
  ['apps/web/app/(main)/(auth)/signin/signin-form.tsx', 6],
  ['apps/web/app/(main)/_home/action-queue-section.tsx', 4],
  ['apps/web/app/(main)/_home/home-sections.tsx', 1],
  ['apps/web/app/(main)/_shared/sending-domain-guard-banner.tsx', 1],
  ['apps/web/app/(main)/_shared/sending-domain-status.tsx', 3],
  ['apps/web/app/(main)/_shell/app-shell.tsx', 4],
  ['apps/web/app/(main)/_shell/page-heading.tsx', 3],
  ['apps/web/app/(main)/audit-logs/audit-log-detail.tsx', 3],
  ['apps/web/app/(main)/audit-logs/audit-logs-view.tsx', 1],
  ['apps/web/app/(main)/engineer-shares/engineer-share-screen.tsx', 15],
  ['apps/web/app/(main)/engineers/(list)/error.tsx', 3],
  ['apps/web/app/(main)/engineers/(list)/loading.tsx', 2],
  ['apps/web/app/(main)/engineers/[id]/detail-section.tsx', 1],
  ['apps/web/app/(main)/engineers/[id]/edit/not-found.tsx', 2],
  ['apps/web/app/(main)/engineers/[id]/engineer-proposal-sections.tsx', 9],
  ['apps/web/app/(main)/engineers/[id]/not-found.tsx', 2],
  ['apps/web/app/(main)/engineers/[id]/page.tsx', 8],
  ['apps/web/app/(main)/engineers/[id]/skill-sheets/page.tsx', 1],
  ['apps/web/app/(main)/engineers/[id]/skill-sheets/skill-sheet-screen.tsx', 12],
  ['apps/web/app/(main)/engineers/_form/engineer-form.tsx', 25],
  ['apps/web/app/(main)/engineers/engineer-ledger-screen.tsx', 9],
  ['apps/web/app/(main)/projects/(list)/error.tsx', 3],
  ['apps/web/app/(main)/projects/(list)/loading.tsx', 2],
  ['apps/web/app/(main)/projects/[id]/candidates/candidate-screen.tsx', 22],
  ['apps/web/app/(main)/projects/[id]/candidates/page.tsx', 2],
  ['apps/web/app/(main)/projects/[id]/edit/not-found.tsx', 2],
  ['apps/web/app/(main)/projects/[id]/not-found.tsx', 2],
  ['apps/web/app/(main)/projects/[id]/page.tsx', 2],
  ['apps/web/app/(main)/projects/[id]/project-detail-screen.tsx', 13],
  ['apps/web/app/(main)/projects/[id]/visibility/visibility-screen.tsx', 26],
  ['apps/web/app/(main)/projects/_form/project-form.tsx', 16],
  ['apps/web/app/(main)/projects/project-list-screen.tsx', 6],
  ['apps/web/app/(main)/proposal-requests/[id]/not-found.tsx', 2],
  ['apps/web/app/(main)/proposal-requests/[id]/proposal-request-respond-screen.tsx', 26],
  ['apps/web/app/(main)/proposal-requests/proposal-request-screen.tsx', 11],
  ['apps/web/app/(main)/proposals/(list)/error.tsx', 2],
  ['apps/web/app/(main)/proposals/(list)/loading.tsx', 2],
  ['apps/web/app/(main)/proposals/(list)/proposal-list-screen.tsx', 8],
  ['apps/web/app/(main)/proposals/[id]/approve/not-found.tsx', 2],
  ['apps/web/app/(main)/proposals/[id]/approve/proposal-approval-screen.tsx', 31],
  ['apps/web/app/(main)/proposals/[id]/edit/not-found.tsx', 2],
  ['apps/web/app/(main)/proposals/[id]/interview/not-found.tsx', 2],
  ['apps/web/app/(main)/proposals/[id]/interview/proposal-interview-screen.tsx', 22],
  ['apps/web/app/(main)/proposals/[id]/not-found.tsx', 2],
  ['apps/web/app/(main)/proposals/[id]/proposal-detail-screen.tsx', 38],
  ['apps/web/app/(main)/proposals/_editor/proposal-editor.tsx', 27],
  ['apps/web/app/(main)/proposals/new/page.tsx', 2],
  ['apps/web/app/(main)/proposals/send-failures/error.tsx', 2],
  ['apps/web/app/(main)/proposals/send-failures/loading.tsx', 2],
  ['apps/web/app/(main)/proposals/send-failures/send-failure-screen.tsx', 17],
  ['apps/web/app/(main)/settings/organization/organization-form.tsx', 9],
  ['apps/web/app/(main)/settings/organization/page.tsx', 5],
  ['apps/web/app/(main)/settings/partner-companies/invite-link-panel.tsx', 1],
  ['apps/web/app/(main)/settings/partner-companies/members-panel.tsx', 8],
  ['apps/web/app/(main)/settings/partner-companies/partner-companies-screen.tsx', 17],
  ['apps/web/app/(main)/settings/retention/retention-screen.tsx', 15],
  ['apps/web/app/(main)/settings/sending-domains/sending-domain-screen.tsx', 16],
  ['apps/web/app/(main)/settings/usage/usage-screen.tsx', 18],
  ['apps/web/app/(main)/skills/skill-dictionary-screen.tsx', 16],
  ['apps/web/app/admin/_components/console-nav.tsx', 2],
  ['apps/web/app/admin/audit-logs/admin-audit-logs-results.tsx', 1],
  ['apps/web/app/admin/audit-logs/admin-audit-logs-view.tsx', 5],
  ['apps/web/app/admin/audit-logs/page.tsx', 2],
  ['apps/web/app/admin/demo/admin-demo-screen.tsx', 16],
  ['apps/web/app/admin/demo/admin-demo-view.tsx', 19],
  ['apps/web/app/admin/layout.tsx', 1],
  ['apps/web/app/admin/monitoring/admin-monitoring-items.tsx', 5],
  ['apps/web/app/admin/monitoring/admin-monitoring-view.tsx', 1],
  ['apps/web/app/admin/monitoring/page.tsx', 2],
  ['apps/web/app/admin/page.tsx', 9],
  ['apps/web/app/admin/signin/admin-signin-form.tsx', 7],
  ['apps/web/app/admin/signin/page.tsx', 2],
  ['apps/web/app/admin/tenants/[id]/contract/deletion-status-screen.tsx', 11],
  ['apps/web/app/admin/tenants/[id]/page.tsx', 15],
  ['apps/web/app/admin/tenants/admin-tenants-list.tsx', 7],
  ['apps/web/app/admin/tenants/new/page.tsx', 2],
  ['apps/web/app/admin/tenants/new/provisioning-form.tsx', 14],
  ['apps/web/app/admin/tenants/page.tsx', 2],
  ['apps/web/app/admin/usage/admin-usage-table.tsx', 2],
  ['apps/web/app/admin/usage/admin-usage-view.tsx', 3],
  ['apps/web/app/admin/usage/page.tsx', 1],
  ['apps/web/app/admin/usage/quota-override-form.tsx', 5],
  ['apps/web/app/global-error.tsx', 1],
]);

/** (j) 8 状態のバリアント — 2026-09-30: 18 ファイル / 30 行。 */
export const UI_RATCHET_BASELINE_J: ReadonlyMap<string, number> = new Map([
  ['apps/web/app/(main)/_home/action-queue-section.tsx', 2],
  ['apps/web/app/(main)/_shell/app-shell.tsx', 1],
  ['apps/web/app/(main)/_shell/page-heading.tsx', 2],
  ['apps/web/app/(main)/audit-logs/audit-logs-view.tsx', 3],
  ['apps/web/app/(main)/projects/[id]/candidates/candidate-screen.tsx', 1],
  ['apps/web/app/(main)/proposals/(list)/proposal-list-screen.tsx', 1],
  ['apps/web/app/admin/_components/console-nav.tsx', 1],
  ['apps/web/app/admin/audit-logs/admin-audit-logs-results.tsx', 1],
  ['apps/web/app/admin/demo/admin-demo-screen.tsx', 1],
  ['apps/web/app/admin/monitoring/admin-monitoring-items.tsx', 1],
  ['apps/web/app/admin/page.tsx', 5],
  ['apps/web/app/admin/tenants/[id]/contract/deletion-status-screen.tsx', 1],
  ['apps/web/app/admin/tenants/[id]/page.tsx', 3],
  ['apps/web/app/admin/tenants/admin-tenants-list.tsx', 3],
  ['apps/web/app/admin/tenants/new/page.tsx', 1],
  ['apps/web/app/admin/tenants/new/provisioning-form.tsx', 1],
  ['apps/web/app/admin/tenants/page.tsx', 1],
  ['apps/web/app/admin/usage/admin-usage-table.tsx', 1],
]);

/** (k) 幅クラスの網羅 — 2026-09-30: 43 ファイル / 43 行。 */
export const UI_RATCHET_BASELINE_K: ReadonlyMap<string, number> = new Map([
  ['apps/web/app/(main)/(auth)/invite/[token]/page.tsx', 1],
  ['apps/web/app/(main)/(auth)/password-reset/confirm/page.tsx', 1],
  ['apps/web/app/(main)/(auth)/password-reset/page.tsx', 1],
  ['apps/web/app/(main)/(auth)/signin/page.tsx', 1],
  ['apps/web/app/(main)/audit-logs/page.tsx', 1],
  ['apps/web/app/(main)/engineer-shares/page.tsx', 1],
  ['apps/web/app/(main)/engineers/(list)/page.tsx', 1],
  ['apps/web/app/(main)/engineers/[id]/edit/page.tsx', 1],
  ['apps/web/app/(main)/engineers/[id]/page.tsx', 1],
  ['apps/web/app/(main)/engineers/[id]/skill-sheets/page.tsx', 1],
  ['apps/web/app/(main)/engineers/new/page.tsx', 1],
  ['apps/web/app/(main)/page.tsx', 1],
  ['apps/web/app/(main)/projects/(list)/page.tsx', 1],
  ['apps/web/app/(main)/projects/[id]/candidates/page.tsx', 1],
  ['apps/web/app/(main)/projects/[id]/edit/page.tsx', 1],
  ['apps/web/app/(main)/projects/[id]/page.tsx', 1],
  ['apps/web/app/(main)/projects/[id]/visibility/page.tsx', 1],
  ['apps/web/app/(main)/projects/new/page.tsx', 1],
  ['apps/web/app/(main)/proposal-requests/[id]/page.tsx', 1],
  ['apps/web/app/(main)/proposal-requests/page.tsx', 1],
  ['apps/web/app/(main)/proposals/(list)/page.tsx', 1],
  ['apps/web/app/(main)/proposals/[id]/approve/page.tsx', 1],
  ['apps/web/app/(main)/proposals/[id]/edit/page.tsx', 1],
  ['apps/web/app/(main)/proposals/[id]/interview/page.tsx', 1],
  ['apps/web/app/(main)/proposals/[id]/page.tsx', 1],
  ['apps/web/app/(main)/proposals/new/page.tsx', 1],
  ['apps/web/app/(main)/proposals/send-failures/page.tsx', 1],
  ['apps/web/app/(main)/settings/organization/page.tsx', 1],
  ['apps/web/app/(main)/settings/partner-companies/page.tsx', 1],
  ['apps/web/app/(main)/settings/retention/page.tsx', 1],
  ['apps/web/app/(main)/settings/sending-domains/page.tsx', 1],
  ['apps/web/app/(main)/settings/usage/page.tsx', 1],
  ['apps/web/app/(main)/skills/page.tsx', 1],
  ['apps/web/app/admin/audit-logs/page.tsx', 1],
  ['apps/web/app/admin/demo/page.tsx', 1],
  ['apps/web/app/admin/monitoring/page.tsx', 1],
  ['apps/web/app/admin/page.tsx', 1],
  ['apps/web/app/admin/signin/page.tsx', 1],
  ['apps/web/app/admin/tenants/[id]/contract/page.tsx', 1],
  ['apps/web/app/admin/tenants/[id]/page.tsx', 1],
  ['apps/web/app/admin/tenants/new/page.tsx', 1],
  ['apps/web/app/admin/tenants/page.tsx', 1],
  ['apps/web/app/admin/usage/page.tsx', 1],
]);

